### ISSUE TITLE
Gamescope is now hosted under ValveSoftware instead of plagman

### ISSUE THREAD

**Issue by grimshins** [akdor1154/gamescope-pkg#21]
Gamescope now lives at https://github.com/ValveSoftware/gamescope , rather than plagman/gamescope

Not sure if this affects anything with regard to your bot automatically generating pull requests, but it appears to be a couple releases behind now. I hope this project continues, as it's been very useful for maintaining an up-to-date Gamescope on Ubuntu 22.04, which has outdated versions of the build dependencies in its repositories.

**Comment by akdor1154** [comment]
thanks for the ping, updated urls and caught up on the releases.
