### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by ThePwnd** [akdor1154/gamescope-pkg#41]
This is likely my own misunderstanding, but I'm struggling to figure out how to use the repo to get Gamescope working.  There are at least 4 different make files, a Python script buried a few layers down that has a main() function, but there aren't any clear instructions in the README file on how to put it all together, and I'm not fluent enough in Python or how make files work to figure it out.  I've tried running a few of the make files, and the Python script, but all of them just throw errors without seeming to accomplish anything.  I've also tried installing the .deb package under the releases tab, but that didn't help me with the missing dependencies for Gamescope.

**Comment by akdor1154** [comment]
If you're just trying to install and use gamescope, the Release is the way to go. It should have the required dependencies specified in the package data so apt etc can pull them in - what difficulty are you having with it?

**Comment by ThePwnd** [comment]
I see where my misunderstanding was.  I read your comment here on the GameScope issue - https://github.com/ValveSoftware/gamescope/issues/731#issuecomment-1406044766 - and in the context of everyone trying to track down missing dependencies or different versions of installed dependencies, I thought the repo you made was _just_ a list of all those dependencies for Pop OS/Ubuntu 22.04, and that I still had to build Gamescope from the source code.  I tested running Gamescope on Left 4 Dead 2 just now and it works.  Thanks for the working version! =)
